// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArkmVg4loFatT5KmvfQQ70QjZ9aSfw84o',
    appId: '1:997178243251:web:ab557369343651b7fcd8c6',
    messagingSenderId: '997178243251',
    projectId: 'bibliotheque-app-bd4ba',
    authDomain: 'bibliotheque-app-bd4ba.firebaseapp.com',
    storageBucket: 'bibliotheque-app-bd4ba.firebasestorage.app',
    measurementId: 'G-XH2J3LNH1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjB3J8C68A1UvxiTjwxnWT1cLGL0sBSYA',
    appId: '1:997178243251:android:3c4d6f374dfa5354fcd8c6',
    messagingSenderId: '997178243251',
    projectId: 'bibliotheque-app-bd4ba',
    storageBucket: 'bibliotheque-app-bd4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6vq_FRWK6jjiBNxPpbkvQZSNyFKzzCg',
    appId: '1:997178243251:ios:2b2c758cc3ac8421fcd8c6',
    messagingSenderId: '997178243251',
    projectId: 'bibliotheque-app-bd4ba',
    storageBucket: 'bibliotheque-app-bd4ba.firebasestorage.app',
    iosBundleId: 'com.example.biblioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW6vq_FRWK6jjiBNxPpbkvQZSNyFKzzCg',
    appId: '1:997178243251:ios:2b2c758cc3ac8421fcd8c6',
    messagingSenderId: '997178243251',
    projectId: 'bibliotheque-app-bd4ba',
    storageBucket: 'bibliotheque-app-bd4ba.firebasestorage.app',
    iosBundleId: 'com.example.biblioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArkmVg4loFatT5KmvfQQ70QjZ9aSfw84o',
    appId: '1:997178243251:web:5945ed4cff97e041fcd8c6',
    messagingSenderId: '997178243251',
    projectId: 'bibliotheque-app-bd4ba',
    authDomain: 'bibliotheque-app-bd4ba.firebaseapp.com',
    storageBucket: 'bibliotheque-app-bd4ba.firebasestorage.app',
    measurementId: 'G-QDTH1XV61V',
  );
}
